### ISSUE TITLE
Homebrew warning: Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by tabacco** [lucagrulla/homebrew-tap#2]
It looks like this property was deprecated in the latest version of Homebrew, and this warning now appears when running ```brew update```:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the lucagrulla/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/lucagrulla/homebrew-tap/Formula/cw.rb:9
```

**Comment by edvina** [comment]
I'm also seeing this deprecation warning for this package.

**Comment by lucagrulla** [comment]
The formula is generated by GoReleaser, the release tools I am currently using. It looks like GoReleaser fixed the change upstream, I need to create a minor release and the warning will be fixed.

I'll do it over the coming week.

**Comment by lucagrulla** [comment]
Fixed.
